services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stream
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      network: host
    volumes:
      - "./:/app"
    restart: always
    depends_on:
      - "db"
    networks:
      default:
        aliases:
          - symfonyTP.local
